services:
  redis:
    image: redis:7.4.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - redis-network

  redisinsight:
    image: redislabs/redisinsight:2.54
    container_name: redisinsight
    ports:
      - "5540:5540"
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge
